[project]
name = "deep-learning-specialization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "black>=24.8.0",
    "jupyter>=1.1.1",
    "numpy>=1.24.4",
]
